### ISSUE TITLE
Integrated logging

### ISSUE THREAD

**Issue by jameschch** [jameschch/LeanOptimization#10]

**Comment by Worthy7** [comment]
It constantly complains that it cannot open the log.txt file because of the multiple threads.

**Comment by jameschch** [comment]
Good you were able to get this far; probably the config is mostly correct. The wiki will help you here:

https://github.com/jameschch/LeanOptimization/wiki/Setup-Guide

> If you wish to enable parallel logging, you will need to modify your lean build as per this commit:
> 
> https://github.com/jameschch/Lean/commit/0115dabd16b0d6e88794b20f7415d76702349c6

...otherwise you will just need to disable logging.

I've completed porting the optimizer logging over to NLog and Lean has done the same. Problem may go away at that point.

**Comment by jameschch** [comment]
Issue will be closed when batcher branch merged to master

**Comment by Worthy7** [comment]
Hi James, thanks for the reply - I totally forgot there is a wiki on Github lol.

With regards to the Logger issue, Lean has an ILoggerHandler interface, which means I think some kind of dependency injection could allow the Optimizer to simply replace the Logger used somehow. But I'm not sure. For now I'll do as you said.

**Comment by jameschch** [comment]
Yes the docs have been neglected so far. Sorry about that.

On 10 April 2017 01:19:37 BST, Worthy7 <notifications@github.com> wrote:

Hi James, thanks for the reply - I totally forgot there is a wiki on Github lol.

With regards to the Logger issue, Lean has an ILoggerHandler interface, which means I think some kind of dependency injection could allow the Optimizer to simply replace the Logger used somehow. But I'm not sure. For now I'll do as you said.

**Comment by jameschch** [comment]
fix merged to master
