### ISSUE TITLE
Better integration with current Lean

### ISSUE THREAD

**Issue by Worthy7** [jameschch/LeanOptimization#12]
Just some ideas:

1) Pull out the data path from the lean config
2) Detect which algorithm to run upon by using reflection on an "IOptimizedAlgorithm" interface

**Comment by jameschch** [comment]
I plan fairly soon to change the config so it just takes a Lean base path and pulls in the config and dll's from there. The idea with the data directory is that it is an override for the config.json setting so you can target different paths in the optimizer that the main clone. Useful when executing remotely.

What would happen if two or more algorithms implement the IOptimizedAlgorithm interface? Also, it's desirable to not require any modification to Lean (even though this is not true currently).

**Comment by Worthy7** [comment]
I see, I suppose you're correct, we can just do some reflection right now on the QCAlgorithm to fine the class we need to work with. 
I can see what you're saying regarding the interface. If we really want to keep LO separate from Lean, then an interface would only cause a dependency loop anyway.

**Comment by jameschch** [comment]
You're right though, the integration needs changing.

**Comment by jameschch** [comment]
The optimizer just supplies a config override. Everything else is lean managed.

On 11 April 2017 01:27:59 BST, Worthy7 <notifications@github.com> wrote:

I see, I suppose you're correct, we can just do some reflection right now on the QCAlgorithm to fine the class we need to work with.
I can see what you're saying regarding the interface. If we really want to keep LO separate from Lean, then an interface would only cause a dependency loop anyway.

**Comment by Worthy7** [comment]
I noticed a few changes recently, is this done now?
