### ISSUE TITLE
Automated Walk Forward with Different Time Divisions

### ISSUE THREAD

**Issue by joshmorris23x** [jameschch/LeanOptimization#18]
This is of particular use when working on an intraday level.

For example, 24,24,24,24,72 hrs (72 is the weekend)

**Comment by jameschch** [comment]
This should now be available in master

https://github.com/jameschch/LeanOptimization/commit/2befbaa6cd10d6e66faa5953f541fd2ebc817a8d

Please feel free to provide feedback on your experiences using this.
