### ISSUE TITLE
Setting "max" of genes in optimization.json not working as expected

### ISSUE THREAD

**Issue by threedots1** [jameschch/LeanOptimization#24]
The maximum value of a gene needs to be set to n+1 to work as would be expected.

For Example if I set the "min" to 1 and the "max" to 10, the actual range that will be tested will be between 1 and 9.

**Comment by jameschch** [comment]
Great spot. The max was just passed into standard Random.Next(min, max) which has an exclusive upper bound. This was fixed with latest commit. This issue will not have affected genes with precision.
