### ISSUE TITLE
Cannot access QC's "Configuration" namespace and Config class

### ISSUE THREAD

**Issue by Doggie52** [jameschch/LeanOptimization#25]
It's my understanding you need to be able to access the Config class in order to use GetInt() and other functions that enable you to actually batch this.

In my IDE I can't seem to build the example algorithm, however, as it tells me it can't find the Configuration namespace nor the Config class.

I can clearly see the project in my IDE, however, so I'm confused. Is there another way I can access configuration values?

Apologies if this should be an issue in Lean's repository instead.

``The type or namespace name 'Configuration' does not exist in the namespace 'QuantConnect' (are you missing an assembly reference?)``

**Comment by Doggie52** [comment]
Sorted this -- was missing a Reference in VS. (https://blogs.msdn.microsoft.com/csharpfaq/2004/04/29/why-did-i-receive-the-error-the-type-or-namespace-namespace-name-does-not-exist-in-the-class-or-namespace-parent-namespace-are-you-missing-an-assembly-reference/)

**Comment by jameschch** [comment]
Yes, you'll see that the example algorithm assembly references the configuration library but the standard lean csharp algorithm library does not.

There are a few problems related to dependency management that I'd like to address at some point.
