### ISSUE TITLE
Exporting of results

### ISSUE THREAD

**Issue by Doggie52** [jameschch/LeanOptimization#26]
Somehow exporting results into something meaningful (as opposed to just a log file) would be very helpful.

For example, for the dynasty walk-forward backtester, it would be helpful to see the parameters found for each new period as well as how those parameters performed going forward.

It would be useful to have the ability to export and parse all of this into csv or json.

**Comment by jameschch** [comment]
At the moment, the log files are formatted to balance readability with parseability. I use a couple of tools to move data around:

https://github.com/jameschch/LeanOptimization/tree/master/Optimization.Toolbox

They parse the last alpha into a json object or a C# dictionary initializer body for use in an algorithm or alternatively directly into an optimization.json so the optimizer can be resumed.

It wouldn't be a major stretch to add another tool that extracted all the data into a raw format.

**Comment by jameschch** [comment]
Logs are now split into optimizer, generations and error.
