### ISSUE TITLE
QuantConnect.FXCM does not have an implementation

### ISSUE THREAD

**Issue by espirulina** [jameschch/LeanOptimization#29]
Hi James, im struggling to run the Optimization. Some bug related to missing QuantConnect.FXCM. I have all references, and cant figure out.

any idea ? thanks
Hi James, im struggling to run the Optimization. Some bug related to missing QuantConnect.FXCM. I have all references, and cant figure out.

any idea ? thanks
![lean_optimization_issue](https://user-images.githubusercontent.com/6436248/38988447-1c01059e-43cb-11e8-809d-5dcde7a0ec89.png)

**Comment by jameschch** [comment]
OK it does sound like a missing reference. What security type are you subscribed to in your algorithm? Is it forex explicitly with the fxcm brokerage? If not make sure you specify the brokerage when adding the subscription.

There are several log files, optimizer.txt is one and each algorithm run will have a guid named log file. Have you had a look at these? Do you want to send them over?

Get back to me if I can help with anything else.

On 19 April 2018 12:13:34 BST, Marco Carola <notifications@github.com> wrote:

Hi James, im struggling to run the Optimization. Some bug related to missing QuantConnect.FXCM. I have all references, and cant figure out.

any idea ? thanks
Hi James, im struggling to run the Optimization. Some bug related to missing QuantConnect.FXCM. I have all references, and cant figure out.

any idea ? thanks

**Comment by espirulina** [comment]
Thanks for the prompt answer !
I was just starting with default algo. SPY security, no changes in base algo / brokerages.
Here is the optimizer.txt log. 
[optimizer.txt](https://github.com/jameschch/LeanOptimization/files/1931207/optimizer.txt)

**Comment by jameschch** [comment]
Depending on what build of lean you use, the optimizer package references need to be in synch. There are minimal references on the optimizer to something like the FXCM brokerage you will need to add from your local clone.
