### ISSUE TITLE
Possible bugs

### ISSUE THREAD

**Issue by Tomtom1583** [jameschch/LeanOptimization#33]
I'm currently having issue with the LeanOptimization code. The following are errors from my build, 

22>C:\Users\Tomi\Documents\Lean\Lean-master\LeanOptimization-master\Optimization\Runner.cs(121,55,121,82): error CS7036: There is no argument given that corresponds to the required formal parameter 'objectStore' of 'LeanEngineAlgorithmHandlers.LeanEngineAlgorithmHandlers(IResultHandler, ISetupHandler, IDataFeed, ITransactionHandler, IRealTimeHandler, IMapFileProvider, IFactorFileProvider, IDataProvider, IAlphaHandler, IObjectStore)'
22>C:\Users\Tomi\Documents\Lean\Lean-master\LeanOptimization-master\Optimization\Handlers\OptimizerResultHandler.cs(133,34,133,54): error CS7036: There is no argument given that corresponds to the required formal parameter 'endDate' of 'BacktestResultPacket.BacktestResultPacket(BacktestNodePacket, BacktestResult, DateTime, DateTime, decimal)'
22>C:\Users\Tomi\Documents\Lean\Lean-master\LeanOptimization-master\Optimization\Handlers\OptimizerResultHandler.cs(251,21,251,41): error CS1061: 'IResultHandler' does not contain a definition for 'SetChartSubscription' and no accessible extension method 'SetChartSubscription' accepting a first argument of type 'IResultHandler' could be found (are you missing a using directive or an assembly reference?)
22>C:\Users\Tomi\Documents\Lean\Lean-master\LeanOptimization-master\Optimization\SingleRunner.cs(157,51,157,78): error CS7036: There is no argument given that corresponds to the required formal parameter 'objectStore' of 'LeanEngineAlgorithmHandlers.LeanEngineAlgorithmHandlers(IResultHandler, ISetupHandler, IDataFeed, ITransactionHandler, IRealTimeHandler, IMapFileProvider, IFactorFileProvider, IDataProvider, IAlphaHandler, IObjectStore)'
22>C:\Users\Tomi\Documents\Lean\Lean-master\LeanOptimization-master\Optimization\Handlers\OptimizerResultHandler.cs(281,28,281,36): error CS1061: 'IResultHandler' does not contain a definition for 'SaveLogs' and no accessible extension method 'SaveLogs' accepting a first argument of type 'IResultHandler' could be found (are you missing a using directive or an assembly reference?)

**Comment by jameschch** [comment]
The optimizer should now be integrated with latest Lean build. Took slightly longer than normal. It is on the to do list to stabilize the target as a nuget package.

**Comment by jameschch** [comment]
Please use the new repo here:
https://github.com/jameschch/LeanParameterOptimization
